remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

description: The First International Workshop on Information Technology Storage Management Specification

theme: jekyll-theme-slate